sudo: false
language: python
cache: pip
dist: xenial
services:
  - docker
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: true
      # This workaround is required until the following issue is resolved:
      # https://github.com/travis-ci/travis-ci/issues/9815
install:
  - pip install -r dev-requirements.txt
  - pip install -e .
before_script:
  - docker-compose up -d
script:
  - ./scripts/copyright_line_check.sh
  - isort --check-only --verbose --recursive graphql_compiler/
  - flake8 --exclude **/snap_*.py graphql_compiler/
  - pydocstyle graphql_compiler/
  - pylint graphql_compiler/
  - bandit -r graphql_compiler/
  - py.test --cov=graphql_compiler graphql_compiler/tests
after_success:
  - docker-compose down
  - coveralls
